/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 BEM-01.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/BEM-01.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[0.6, -0.9, 0]} scale={0.017}>
        <mesh geometry={nodes.BEM01_v17_1.geometry} material={materials['Glass_-_Heavy_Color']} />
        <mesh geometry={nodes.BEM01_v17_2.geometry} material={materials['Glass_-_Heavy_Color_(Blue)']} />
        <mesh geometry={nodes.BEM01_v17_3.geometry} material={materials['Opaque(127,127,127)']} />
        <mesh geometry={nodes.BEM01_v17_4.geometry} material={materials['Opaque(76,76,76)']} />
        <mesh geometry={nodes.BEM01_v17_5.geometry} material={materials['Opaque(232,113,8)']} />
        <mesh geometry={nodes.BEM01_v17_6.geometry} material={materials['Opaque(229,229,229)']} />
        <mesh geometry={nodes.BEM01_v17_7.geometry} material={materials['Opaque(165,132,0)']} />
        <mesh geometry={nodes.BEM01_v17_8.geometry} material={materials['Opaque(165,158,150)']} />
        <mesh geometry={nodes.BEM01_v17_9.geometry} material={materials['Opaque(202,209,238)']} />
        <mesh geometry={nodes.BEM01_v17_10.geometry} material={materials['Opaque(2,61,210)']} />
        <mesh geometry={nodes.BEM01_v17_11.geometry} material={materials['Steel_-_Satin']} />
        <mesh geometry={nodes.BEM01_v17_12.geometry} material={materials['Polymide_(Kapton)']} />
        <mesh geometry={nodes.BEM01_v17_13.geometry} material={materials['Opaque(25,25,25)']} />
        <mesh geometry={nodes.BEM01_v17_14.geometry} material={materials['Opaque(160,160,160)']} />
        <mesh geometry={nodes.BEM01_v17_15.geometry} material={materials['Opaque(153,130,94)']} />
        <mesh geometry={nodes.BEM01_v17_16.geometry} material={materials['Opaque(68,119,102)']} />
        <mesh geometry={nodes.BEM01_v17_17.geometry} material={materials['Opaque(244,229,167)']} />
        <mesh geometry={nodes.BEM01_v17_18.geometry} material={materials['Opaque(230,230,230)']} />
        <mesh geometry={nodes.BEM01_v17_19.geometry} material={materials['Paek_(Beige)']} />
        <mesh geometry={nodes.BEM01_v17_20.geometry} material={materials['Opaque(105,105,105)']} />
        <mesh geometry={nodes.BEM01_v17_21.geometry} material={materials['Opaque(88,88,88)']} />
        <mesh geometry={nodes.BEM01_v17_22.geometry} material={materials['Opaque(255,225,0)']} />
        <mesh geometry={nodes.BEM01_v17_23.geometry} material={materials['Opaque(255,191,0)']} />
        <mesh geometry={nodes.BEM01_v17_24.geometry} material={materials['Opaque(28,28,28)']} />
        <mesh geometry={nodes.BEM01_v17_25.geometry} material={materials['Opaque(239,239,239)']} />
        <mesh geometry={nodes.BEM01_v17_26.geometry} material={materials['Opaque(38,38,38)']} />
        <mesh geometry={nodes.BEM01_v17_27.geometry} material={materials['Opaque(63,63,63)']} />
      </group>
    </group>
  )
}

useGLTF.preload('/BEM-01.glb')
