/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 Magikarp_Bright.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Magikarp.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.02, 0]} rotation={[0.7,-0.7,0]} scale={0.03}>
        <mesh geometry={nodes.Magikarp_v61_1.geometry} material={materials['Plastic_-_Glossy_(Black)']} />
        <mesh geometry={nodes.Magikarp_v61_2.geometry} material={materials['Aluminum_-_Satin']} />
        <mesh geometry={nodes.Magikarp_v61_3.geometry} material={materials.KaptonTape} />
        <mesh geometry={nodes.Magikarp_v61_4.geometry} material={materials['Steel_-_Satin']} />
        <mesh geometry={nodes.Magikarp_v61_5.geometry} material={materials['Paint_-_Enamel_Glossy_(Green)']} />
        <mesh geometry={nodes.Magikarp_v61_6.geometry} material={materials['Plastic_-_Glossy_(Red)']} />
        <mesh geometry={nodes.Magikarp_v61_7.geometry} material={materials['Paint_-_Enamel_Glossy_(Black)']} />
        <mesh geometry={nodes.Magikarp_v61_8.geometry} material={materials['Nylon_6-6_(White)']} />
        <mesh geometry={nodes.Magikarp_v61_9.geometry} material={materials['Opaque(0,128,0)']} />
        <mesh geometry={nodes.Magikarp_v61_10.geometry} material={materials['Opaque(160,160,160)']} />
        <mesh geometry={nodes.Magikarp_v61_11.geometry} material={materials['Opaque(212,212,212)']} />
        <mesh geometry={nodes.Magikarp_v61_12.geometry} material={materials['Opaque(245,245,245)']} />
        <mesh geometry={nodes.Magikarp_v61_13.geometry} material={materials['Opaque(73,73,73)']} />
        <mesh geometry={nodes.Magikarp_v61_14.geometry} material={materials['Opaque(153,153,153)']} />
        <mesh geometry={nodes.Magikarp_v61_15.geometry} material={materials['Opaque(204,204,204)']} />
        <mesh geometry={nodes.Magikarp_v61_16.geometry} material={materials['Opaque(85,0,255)']} />
        <mesh geometry={nodes.Magikarp_v61_17.geometry} material={materials['Opaque(255,255,255)']} />
        <mesh geometry={nodes.Magikarp_v61_18.geometry} material={materials['Opaque(63,63,63)']} />
        <mesh geometry={nodes.Magikarp_v61_19.geometry} material={materials['Opaque(170,85,0)']} />
        <mesh geometry={nodes.Magikarp_v61_20.geometry} material={materials['Opaque(0,0,127)']} />
        <mesh geometry={nodes.Magikarp_v61_21.geometry} material={materials['Opaque(63,63,63)_1']} />
        <mesh geometry={nodes.Magikarp_v61_22.geometry} material={materials['Opaque(245,245,246)']} />
        <mesh geometry={nodes.Magikarp_v61_23.geometry} material={materials['Opaque(196,53,39)']} />
        <mesh geometry={nodes.Magikarp_v61_24.geometry} material={materials['Opaque(68,150,72)']} />
        <mesh geometry={nodes.Magikarp_v61_25.geometry} material={materials['Opaque(229,202,158)']} />
        <mesh geometry={nodes.Magikarp_v61_26.geometry} material={materials['Opaque(246,246,243)']} />
        <mesh geometry={nodes.Magikarp_v61_27.geometry} material={materials['Opaque(64,64,64)']} />
        <mesh geometry={nodes.Magikarp_v61_28.geometry} material={materials['Opaque(202,209,238)']} />
        <mesh geometry={nodes.Magikarp_v61_29.geometry} material={materials['Opaque(128,128,128)']} />
        <mesh geometry={nodes.Magikarp_v61_30.geometry} material={materials['Opaque(191,191,191)']} />
        <mesh geometry={nodes.Magikarp_v61_31.geometry} material={materials['Opaque(251,212,169)']} />
        <mesh geometry={nodes.Magikarp_v61_32.geometry} material={materials['Opaque(120,110,70)']} />
        <mesh geometry={nodes.Magikarp_v61_33.geometry} material={materials['Opaque(228,180,12)']} />
        <mesh geometry={nodes.Magikarp_v61_34.geometry} material={materials['Opaque(10,10,10)']} />
        <mesh geometry={nodes.Magikarp_v61_35.geometry} material={materials['Opaque(250,250,128)']} />
        <mesh geometry={nodes.Magikarp_v61_36.geometry} material={materials['Opaque(90,90,90)']} />
        <mesh geometry={nodes.Magikarp_v61_37.geometry} material={materials['Opaque(0,192,0)']} />
        <mesh geometry={nodes.Magikarp_v61_38.geometry} material={materials['Opaque(244,244,244)']} />
        <mesh geometry={nodes.Magikarp_v61_39.geometry} material={materials['Opaque(237,206,195)']} />
        <mesh geometry={nodes.Magikarp_v61_40.geometry} material={materials['Opaque(25,25,25)']} />
        <mesh geometry={nodes.Magikarp_v61_41.geometry} material={materials['Opaque(192,192,192)']} />
        <mesh geometry={nodes.Magikarp_v61_42.geometry} material={materials['Opaque(207,201,181)']} />
        <mesh geometry={nodes.Magikarp_v61_43.geometry} material={materials['Opaque(255,255,244)']} />
        <mesh geometry={nodes.Magikarp_v61_44.geometry} material={materials['Opaque(0,128,192)']} />
        <mesh geometry={nodes.Magikarp_v61_45.geometry} material={materials['Opaque(205,205,205)']} />
        <mesh geometry={nodes.Magikarp_v61_46.geometry} material={materials['Opaque(220,160,15)']} />
        <mesh geometry={nodes.Magikarp_v61_47.geometry} material={materials['Opaque(71,71,71)']} />
        <mesh geometry={nodes.Magikarp_v61_48.geometry} material={materials['Opaque(31,191,31)']} />
        <mesh geometry={nodes.Magikarp_v61_49.geometry} material={materials['Opaque(222,179,89)']} />
        <mesh geometry={nodes.Magikarp_v61_50.geometry} material={materials['Opaque(100,153,100)']} />
        <mesh geometry={nodes.Magikarp_v61_51.geometry} material={materials['Opaque(51,51,51)']} />
        <mesh geometry={nodes.Magikarp_v61_52.geometry} material={materials['Opaque(170,170,127)']} />
        <mesh geometry={nodes.Magikarp_v61_53.geometry} material={materials['Opaque(105,77,59)']} />
        <mesh geometry={nodes.Magikarp_v61_54.geometry} material={materials['Opaque(226,226,226)']} />
        <mesh geometry={nodes.Magikarp_v61_55.geometry} material={materials['Opaque(249,200,125)']} />
        <mesh geometry={nodes.Magikarp_v61_56.geometry} material={materials['Opaque(231,163,50)']} />
        <mesh geometry={nodes.Magikarp_v61_57.geometry} material={materials['Opaque(234,230,231)']} />
        <mesh geometry={nodes.Magikarp_v61_58.geometry} material={materials['Opaque(229,229,229)']} />
        <mesh geometry={nodes.Magikarp_v61_59.geometry} material={materials['Opaque(194,166,129)']} />
        <mesh geometry={nodes.Magikarp_v61_60.geometry} material={materials['Glass_(Grey)']} />
      </group>
    </group>
  )
}

useGLTF.preload('/Magikarp.glb')
